# Site/SEO settings
email: icetime963@gmail.com
permalink: /:year/:month/:day/:title/
google_analytics: 

title: HEPHAI
description: 
url: "https://bingsu-kun.github.io/"
baseurl: ""
twitter_username: 
default_img: 

# Profile settings
name: HepHai
profile_img: 
profile: 
social:
  github: https://github.com/bingsu-kun

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed
