# Site/SEO settings
email: icetime963@gmail.com
permalink: /:year/:month/:day/:title/
google_analytics: 

title: HEPHAI's devlog
description: Mainly about coding, also my hobbys.
url: "https://bingsu-kun.github.io"
baseurl: ""
twitter_username: 
default_img: "https://user-images.githubusercontent.com/57391343/109517333-7a709080-7aec-11eb-8ead-6edbce8b9b74.png"

# Profile settings
name: Hephai (JangHoon Lee)
profile_img: "https://user-images.githubusercontent.com/57391343/109517333-7a709080-7aec-11eb-8ead-6edbce8b9b74.png"
profile: Interested in backend dev, cloud engineering, blockchain. Usually do camping, fishing, cooking, exercising on holiday. And also enjoy editing videos that I took this hobbys.
social:
  github: https://github.com/bingsu-kun

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed
